### ISSUE TITLE
need more detailed output

### ISSUE THREAD

**Issue by bmalets** [vslavik/diff-pdf#32]
Hi @vslavik,

   Looks like your Pdf compare utility is the best for linux systems. Thanks.
   I can check for a differences of two pdf files using this command:
      `$diff-pdf -v 1.pdf 2.pdf`

  But I see only `page 4 differences` in output...
  Is it possible to make detailed output?
  For example: count of errors or something like "git diff"

  P.S. in my case, pdf files may have only one difference on page, 
          but using this utility I can check only for an existanse of differences... not for count

Thanks kindly!

**Comment by vslavik** [comment]
Did you read this repo's description? If you want functionality changes, implement them and submit a PR.

That said, I don't even have any idea how could it show any more info than this meaningfully. If you want to see the details of the changes, use the GUI mode — that's what it is *for*.
