### ISSUE TITLE
[bug] error without any option

### ISSUE THREAD

**Issue by mattia-b89** [vslavik/diff-pdf#40]
If I launch the program without any option (i.e. --view),
the program exits with this error:
```
$ ./diff-pdf ~/Downloads/unicocdo.pdf  ~/Downloads/unicocdo\(1\).pdf 
14:52:15: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
and diff-pdf used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8).
14:52:15: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1009,wx containers,compatible with 2.8),
and your program used 3.0 (wchar_t,compiler with C++ ABI 1010,wx containers,compatible with 2.8).
```

**Comment by vslavik** [comment]
Please see this project’s description.

Please also *read* the error message, it tells you exactly what you did wrong — i.e. miscompiled things by doing some haphazard juggling of include paths and tricking the compiler into using a wrong library.  If it’s still unclear to you, google “Warning: Mismatch between the program and library build versions detected” for further explanations.

**Comment by mattia-b89** [comment]
oh, sorry the OP is cut out
the above is the error when I launch without any option
BUT
when I launch the same command plus `--view` everything works fine

**Comment by vslavik** [comment]
Please see this project’s description.

And you’re wrong that “everything works fine”, you screwed up compilation in a bad and potentially dangerous way. If it starts crashing for you, don’t file new bugs for the crashes — *this* would be the reason for them.
