### ISSUE TITLE
bug with --output-pdf when files are equal

### ISSUE THREAD

**Issue by sygi** [vslavik/diff-pdf#42]
Hello,
thanks for your work on the library and putting it online :)

I have found a problem when you calculate the diff for the two identical pages. With `--view` it works flawlessly, but when I do `--output-diff` I get a cluttered file, like in the [screenshot](http://students.mimuw.edu.pl/~js319394/2016-06-15-185131_1243x800_scrot.png).

I have this problem on Ubuntu 14.04. with the newest libraries:
```
[master][~/projekty/diff-pdf]$ apt-show-versions libpoppler-glib-dev poppler-utils libwxgtk3.0-dev       
libpoppler-glib-dev:amd64/trusty-security 0.24.5-2ubuntu4.4 uptodate
libwxgtk3.0-dev:amd64/trusty 3.0.0-2 uptodate
poppler-utils:amd64/trusty-security 0.24.5-2ubuntu4.4 uptodate
```

It looks strange and seems to be actually a bug in the `poppler_page_render`, but I am not committed to dig further. The workaround is to change it to `poppler_page_render_for_printing`. Merge it if you find it reasonable -- I'm sending a pull request.

**Comment by vslavik** [comment]
Please do not create duplicate issues — a PR is an issue, it makes absolutely no sense to create both for the same thing at the same time.
