### ISSUE TITLE
Size of the output PDFs

### ISSUE THREAD

**Issue by swajnautcz** [vslavik/diff-pdf#45]
Hi,

first off, what a great tool, I really like it.

I'm using this to compare two PDF files generated by LaTeX, about 10 MB each. There are only a few changes in them, yet the diff PDF is about 110 MB. I wonder why is that? Does diff-pdf replace the fonts by outlines?

I was trying to compress the pdf by using:

> gswin32c.exe -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dNOPAUSE -dQUIET -dBATCH -sOutputFile=diff01-compressed.pdf diff01.pdf

But that only makes the file larger, not smaller. I was wondering if there is a way around this?

**Comment by vslavik** [comment]
> Does diff-pdf replace the fonts by outlines?

No, bitmaps. You can see for yourself in the code, that's why it's open source.

**Comment by swajnautcz** [comment]
I'm not so skilled with cairo I'm afraid. Are those bitmaps stored as lossy or lossless? I actually can't tell from looking at the source :(.

**Comment by vslavik** [comment]
There's a process by which unskilled people become skilled: it's called *learning*.

Please see this project's description. PRs are welcome, but don't expect support and certainly don't expect me to spend time satisfying your idle curiosity about how the code works. You have the code at your disposal, read it (in depth, with docs, not a 3-seconds "I don't understand, I'm done" glance).

**Comment by swajnautcz** [comment]
Well, the time alone you spent writing these hollow responses could be put to a better use. But I get it, you're a busy and important person. However, you do not seem entirely educated yourself. There are both shorter and more polite ways to say fuck off, which would have saved time for us both.

**Comment by vslavik** [comment]
> Well, the time alone you spent writing these hollow responses could be put to a better use.

Yes, it could, but somebody has to teach you some manners if you don't know how to behave.

> There are both shorter and more polite ways

Kindly tone down your unreasonable entitlement. I owe you nothing. And *you* don't get to lecture anybody about politeness with your entitlement, arrogance and language. People like you are why developers burn out on Open Source. They are also the reason why this project sets expectations very clearly in its description — i.e. a short and polite way to tell you what to expect. Too bad you completely ignored it...
