### ISSUE TITLE
Status code returns a value of 1

### ISSUE THREAD

**Issue by pherrera87** [vslavik/diff-pdf#46]
Hello,
I have a problem when I run the command:
 `C: \ diff-pdf \ diff-pdf.exe C: \ test \ diff-pdf \ a.pdf C: \ test \ diff-pdf \ B.pdf --output-diff = C: \ test \ diff-pdf \ diff.pdf` 
from the terminal windows me correctly creates pdf motioning differences, but when I run from my java code tells me that the status code is one whose value should be 0.
Then leave the code in java with which I tried, I do not know why this happens.

`public void testTest() throws ConversionException, TemplateException, SecurityException, InterruptedException, IOException {
		 	List <String> paramsList = new ArrayList<>();	       
	        paramsList.add("C:\\OpenKM\\tomcat-7.0.27-6.4-mysql\\bin\\diff-pdf\\diff-pdf");
	        paramsList.add("C:\\Users\\DXD\\Desktop\\diff-pdf\\a.pdf");
	        paramsList.add("C:\\Users\\DXD\\Desktop\\diff-pdf\\b.pdf");
	        paramsList.add("--output-diff=C:\\Users\\DXD\\Desktop\\diff-pdf\\dif.pdf");
	        	 
	        int status=0;
	        try{	    	 
	            FileLogger.info("test", "Executing command: " + paramsList.toString());
	            String params[] = new String[paramsList.size()];
	            
	            ProcessBuilder pb = new ProcessBuilder(paramsList.toArray(params));
	            pb.redirectErrorStream(true); // Error is redirected to in
	            
	            
	            //pb.redirectError(new File("C:\\Users\\DXD\\Desktop\\diff-pdf\\error.txt"));
	            Process proc = pb.start();
	          
	            String line;             
	            BufferedReader in = new BufferedReader(new InputStreamReader(proc.getInputStream()));             
	            while ((line = in.readLine()) != null) {
	                FileLogger.info("test", line);
	            }
	            
	            status = proc.waitFor();
	            
	            // Clean-up
	            proc.destroy();
	            FileLogger.info("test", "End execution command.");	        		           
           	            
	        }catch (IOException ex) {
	                System.out.println("Excepción: ");
	                ex.printStackTrace();
	                throw new IOException("Could not execute: " + paramsList.toString(), ex);
	        }catch (InterruptedException ex) {
	            throw new RuntimeException("Could not execute: " + paramsList.toString(), ex);
	        } 
	        if (status != 0) {
	            throw new RuntimeException("Conversion failed with status code: " + status + ". Command executed: " + paramsList.toString());
	        }
	}`

I hope you can help me, I look forward to your reply please.
A greeting and thanks in advance.

**Comment by vslavik** [comment]
As with everything else, != 0 code indicates an error — apparently in your code that has nothing at all to do with this project. Hint: `\` is an escape character in Java strings.

**Comment by pherrera87** [comment]
This is not the problem because I have changed routes using "/" and "\\" for example: 
"C:/test/diff-pdf/a.pdf" or "C:\\test\\diff-pdf \\a.pdf "
But, the status code continuous returning a value of 1.
Greetings,

**Comment by vslavik** [comment]
Then please 1. read this project’s description, 2. use your debugger to investigate what the problem is and 3. submit a PR fixing it.

Thanks in advance!
