### ISSUE TITLE
invalid image coordinates 

### ISSUE THREAD

**Issue by loue58** [vslavik/diff-pdf#48]
The program is working fine on most of my files.  I get an error on these two.

`diff-pdf --view test1a.pdf test1b.pdf`

Thanks for the code!  

[test1a.pdf](https://github.com/vslavik/diff-pdf/files/560681/test1a.pdf)
[test1b.pdf](https://github.com/vslavik/diff-pdf/files/560682/test1b.pdf)
![invalid image cooridinates message](https://cloud.githubusercontent.com/assets/12474092/19839421/a7ad761e-9eb7-11e6-9a11-79d02a4dd02c.JPG)

**Comment by vslavik** [comment]
Kindly read the project's description.
