### ISSUE TITLE
yum install... wxGTK-devel should be wxGTK3-devel, at least on Fedora 24

### ISSUE THREAD

**Issue by seanf** [vslavik/diff-pdf#49]
The build instructions for CentOS say to install (among other things) the package wxGTK-devel. I think Fedora should be similar, but I found I had to install wxGTK3-devel.

**Comment by vslavik** [comment]
Kindly read this repository description. If you *know* what’s wrong, why do you create an issue instead of making a (trivial) PR to update the instructions?

**Comment by seanf** [comment]
Because it wasn't trivial to ensure the instructions for Fedora would be accurate, let alone CentOS, but I wanted to report the information in case it could help someone else.

**Comment by vslavik** [comment]
> Because it wasn't trivial

Oh *please*.
